### PR TITLE
Flake8: Fix and enable E503 error

### PR DESCRIPTION
**Pull request by cutwater**
* Fix E503 errors in project's codebase.
* Enable check `E503: Line is too long`.

### CODE REVIEW

**Comment by mkanoor** [comment]
@cutwater Their is a error in github actions
https://github.com/ansible/pinakes/runs/5662292431?check_suite_focus=true

**Comment by cutwater** [comment]
@mkanoor rebased it

**Comment by mkanoor** [comment]
@cutwater Still seeing lint with black errors https://github.com/ansible/pinakes/runs/5664106462?check_suite_focus=true

**Comment by cutwater** [comment]
@mkanoor that's an old status

**Review by mkanoor — APPROVED** [review]

**Pull request merged**
