### PR TITLE
[SSP-292] Use a customized get_object_or_404 to handle non integer id

### PR DESCRIPTION
**Pull request by bzwei**
https://issues.redhat.com/browse/SSP-2928

Default get_object_or_404 method does not raise 404 if the id is a string. This attempt is to catch the DB error and raise 404 so the user will not see a 500 error.

### CODE REVIEW

**Review by hsong-rh — APPROVED** [review]

**Review by eclarizio — COMMENTED** [review]
Hmm, that kinda sucks that the django provided shortcut `get_object_or_404` doesn't already handle this case. Oh well, I guess.

Looks like the title is using the wrong SSP ID, if you can change that and then close/reopen the PR it should automatically link.

**Comment by mkanoor** [comment]
@bzwei 
I tested this from a django console. and it seems to work with both strings and integers for non existent objects.
This is for a non existent string id
```
obj = get_object_or_404(Source,pk="10")
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/django/shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/django/db/models/query.py", line 496, in get
    raise self.model.DoesNotExist(
pinakes.main.models.Source.DoesNotExist: Source matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/app-root/lib64/python3.9/site-packages/django/shortcuts.py", line 87, in get_object_or_404
    raise Http404(
django.http.response.Http404: No Source matches the given query.
```

This is for a integer id
```
obj = get_object_or_404(Source,pk=10)
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/django/shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/django/db/models/query.py", line 496, in get
    raise self.model.DoesNotExist(
pinakes.main.models.Source.DoesNotExist: Source matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/app-root/lib64/python3.9/site-packages/django/shortcuts.py", line 87, in get_object_or_404
    raise Http404(
django.http.response.Http404: No Source matches the given query.
```

**Comment by mkanoor** [comment]
@bzwei Is this happening because we have been using integer id's as strings? if we had stuck to integer ids would this issue be resolved. Are we missing a piece that validates the incoming parameters like we used on the cloud (openapi parser).  Is there a python equivalent of this https://github.com/ota42y/openapi_parser

**Comment by mkanoor** [comment]
@bzwei Should we be catching the value Error exception and converting it to 400 Bad Parameter
somewere here
https://github.com/ansible/pinakes/blob/43cafdd808b4a4c845a460c00175d4b35194f9fa/pinakes/common/exception_handler.py#L11

**Comment by bzwei** [comment]
@mkanoor ValueError does not automatically translate into a 400 error. We could catch this error in custom_exception_handler, but it should be the last defend. The proper way may be still to validate the user input on purpose. The method `get_object_by_id_or_404` introduced in this PR is to be called on demand. It does not need to replace every `get_object_or_404` call. 
Similarly we could catch IntegrityError in custom_exception_handler, but we may still want to handle error in each particular call for PR #518

**Comment by bzwei** [comment]
Withhold this PR until we can introduce a proper validator for path variables.

**Pull request closed without merging**
